version: "3.9"

networks:
  etl-template:

volumes:
  etl-template-backend-cache:
  etl-template-db-volume:

services:
  etl-template-db:
    restart: "no"
    image: "postgres:15-alpine"
    container_name: etl-template-db-development
    networks:
      etl-template:
    ports:
      - "5432:5432"
    volumes:
      - "etl-template-db-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "etl_template"
      POSTGRES_USER: "etl_template_user"
      POSTGRES_PASSWORD: "etl_template_password"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  etl-template-backend:
    restart: "no"
    build:
      context: ../../backend/
      dockerfile: ../docker/development/backend/Dockerfile
    container_name: etl-template-backend-development
    depends_on:
      - etl-template-db
    networks:
      etl-template:
    ports:
        - "8000:8000"
    volumes:
      - "../../backend/:/app/"
      - "./backend/scripts/:/scripts/"
      - "etl-template-backend-cache:$HOME/.cache/pip"
    environment:
      SECRET_KEY: "fd!=^e#_pukzl#+2@apf-i2x7e*-%6@ucwg%fo9@ic-s(*t7jh"
      POSTGRES_DB_HOST: "etl-template-db"
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: "etl_template"
      POSTGRES_DB_USER: "etl_template_user"
      POSTGRES_DB_PASSWORD: "etl_template_password"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health-check/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: [ "/scripts/run-development.sh" ]
