# Generated by Django 4.2.20 on 2025-05-01 06:29

from django.db import migrations, models

import modules.load.domain.value_objects


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=modules.load.domain.value_objects.DataId.new,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text='Example: {"full_name": "John Doe", "age": 30, "is_satisfied": true}'
                    ),
                ),
            ],
            options={
                "verbose_name": "Data",
                "verbose_name_plural": "Data",
            },
        ),
    ]
