ORDERING_QUERY_PARAMETER_NAME = "ordering"

PAGINATION_OFFSET_QUERY_PARAMETER_NAME = "offset"
PAGINATION_LIMIT_QUERY_PARAMETER_NAME = "records_per_page"
PAGINATION_RESULTS_NAME = "results"
PAGINATION_COUNT_NAME = "count"
PAGINATION_NEXT_LINK_NAME = "next"
PAGINATION_PREVIOUS_LINK_NAME = "previous"

ERROR_DETAIL_KEY = "detail"
