# Generated by Django 4.2.20 on 2025-04-01 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 4, 1, 19, 22, 0, 366433, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_file_name", models.CharField(max_length=255)),
                ("saved_file_name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
