# Generated by Django 4.2.20 on 2025-04-07 15:27

from django.db import migrations, models
import modules.common.time
import modules.extract.domain.value_objects


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=modules.common.time.get_currect_timestamp,
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=modules.extract.domain.value_objects.FileId.new,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_file_name", models.CharField(max_length=255)),
                ("saved_file_name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
