# Generated by Django 4.2.20 on 2025-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_file_name", models.CharField(max_length=256)),
                ("saved_file_name", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
